#!/bin/bash

riscv64-linux-gnu-as -o mecrisp-quintus-linux-rv32im.o mecrisp-quintus-linux-rv32im.s -march=rv32im
riscv64-linux-gnu-ld -T mecrisp.ld -z max-page-size=4096 -o mecrisp-quintus-linux-rv32im mecrisp-quintus-linux-rv32im.o -m elf32lriscv
riscv64-linux-gnu-objdump -Mnumeric -D mecrisp-quintus-linux-rv32im > mecrisp-quintus-linux-rv32im.list
