#!/bin/bash

mkdir build
rm -f build/*

echo "Synthesize design..."

if
  yosys  -q -p "synth_ecp5 -top ulx3s -json build/ulx3s.json -abc2 -abc9" ulx3s.v;
then
  echo "Place and Route..."
  nextpnr-ecp5 --85k --package CABGA381 --json build/ulx3s.json --lpf ulx3s_v20.lpf --textcfg build/ulx3s.config --ignore-loops

  echo "Create Bitstream..."
  ecppack --input build/ulx3s.config --bit ulx3s.bit

  echo "Finished."
fi

rm -f build/*
