#!/bin/bash

mkdir -p build
rm -f build/*

echo "Synthesize design..."
yosys  -q -p "synth_ice40 -top top -json build/nandland.json -blif build/nandland.blif -relut -no-rw-check" nandland.v

echo "Place and Route..."
nextpnr-ice40 --freq 25 --hx1k --package vq100 --asc build/nandland.txt --pcf nandland.pcf --json build/nandland.json --ignore-loops --pcf-allow-unconstrained

echo "Create Bitstream..."
icepack build/nandland.txt nandland.bin -s

rm -f build/*

echo "Finished."
