#!/bin/bash

# Usage: buildcore forth-source precompiled-binary

{
   echo -e "compiletoflash\n"
   cat "$1"
   echo -e "compiletoflash here hex DABBAD00 !\n"
   # cat -
} | ./quintusemu-pic32mx570 mecrisp-quintus-pic32mx570f512l-boot.bin mecrisp-quintus-pic32mx570f512l-text.bin

echo -e ""

mv coredump.bin "$2"
