#!/bin/bash

cd quintusemu-source
fpc -XX -O3 quintusemu-pic32mx570
mv quintusemu-pic32mx570 ..
rm *.o
cd ..

cat ../common/conditional.txt ../common/disassembler-mips.txt ../common/fixpt-math-lib.fs ../common/dictionary-tools.txt ../common/multitask.txt ../common/multitask-debug.txt > included.txt

./buildcore included.txt mecrisp-quintus-pic32mx570f512l-text-with-tools.bin

# Cat both files together. Use physical addresses instead of 0xBFC00000 and 0xBD000000 !

srec_cat mecrisp-quintus-pic32mx570f512l-boot.bin -binary -offset 0x1FC00000 mecrisp-quintus-pic32mx570f512l-text-with-tools.bin -binary -offset 0x1D000000 -output mecrisp-quintus-pic32mx570f512l-with-tools.hex

# Just to have the same Intel HEX format...

mipsel-linux-gnu-objcopy mecrisp-quintus-pic32mx570f512l-with-tools.hex -I ihex mecrisp-quintus-pic32mx570f512l-with-tools.hex -O ihex

