#!/bin/bash

# Usage: buildcore quintusemu mecrisp-quintus-binary forth-source precompiled-binary

{
   echo -e "compiletoflash\n"
   cat "$3"
   echo -e "compiletoflash here hex DABBAD00 !\n"
   # cat -
} | "$1" "$2"

echo -e ""

mv coredump.bin "$4"
