#!/bin/bash

mkdir -p build
rm -f build/*

echo "Synthesize design..."

if
  yosys  -q -p "synth_ice40 -top icestick -json build/icestick.json -blif build/icestick.blif -abc2 -relut -no-rw-check" icestick.v;
then
  echo "Place and Route..."
  nextpnr-ice40 --freq 48 --hx1k --package tq144 --asc build/icestick.txt --pcf icestick.pcf --json build/icestick.json --ignore-loops --pcf-allow-unconstrained --seed 31
  echo "Create Bitstream..."
  icepack build/icestick.txt build/icestick0.bin
  icemulti -p0 build/icestick0.bin > icestick.bin
  echo "Finished."
fi

rm -f build/*
